### ISSUE TITLE
Getting YAML errors on Dedicated Server

### ISSUE THREAD

**Issue by Vacknyr** [RavienGaming/Reforged-Eden-2#189]
### Reforged Eden 2 Build Number

15

### Game mode

Dedicated Server

### Tested in vanilla

Issue does not happen in vanilla

### Description of issue

Error: YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected 'SequenceStart', got 'MappingStart' (at Line: 1, Col: 1, Idx: 0).
 

### Error code from console or log (Optional)

7/5/2024 8:44:05 AM	Error: YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected 'SequenceStart', got 'MappingStart' (at Line: 1, Col: 1, Idx: 0).
   at YamlDotNet.Core.EventReader.Expect[T]()
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(EventReader reader, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at EPG.SectorYamlData.Deserialize(String path)
   at EmpAdminHelper.Funktionen.Fill_Playfields(Boolean blnForceReadMainSector): Further Infos: Fill_Playfields Yaml:  -

**Comment by RavienGaming** [comment]
This looks like a server configuration problem especially because it references EAH. There's not much I could do to help beyond whatever is already put in the Reforged Eden configuration guide and server setup directions on the workshop.
You could try reaching out on the official discord to see if anyone would know where the problem lies. It could be your dedicated.yaml or gameoptions.yaml files are corrupt or improperly configured.
