### ISSUE TITLE
EAH spitting out error

### ISSUE THREAD

**Issue by wunz1** [RavienGaming/Reforged-Eden-2#404]
### Reforged Eden 2 Build Number

25

### Game mode

Dedicated Server

### Tested in vanilla

Not tested in vanilla or not applicable

### Description of issue

Loaded RE2 on the server for the first time,everytime server starts EAH spits out a error,

### Error code from console or log (Optional)

Error: YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Expected 'SequenceStart', got 'MappingStart' (at Line: 1, Col: 1, Idx: 0).
   at YamlDotNet.Core.EventReader.Expect[T]()
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(EventReader reader, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at EPG.SectorYamlData.Deserialize(String path)
   at EmpAdminHelper.Funktionen.Fill_Playfields(Boolean blnForceReadMainSector): Further Infos: Fill_Playfields Yaml:

**Comment by RavienGaming** [comment]
No idea what that error would be from as those logs say nothing about it, but EAH is an Eleon thing so it's not anything I would be able to fix in the scenario anyway. Assuming that you configured the scenario and server properly, you'd need to follow the below attached directions to report it to Eleon assuming it happens using a vanilla scenario.
You might want to triple check you followed all the steps to configure everything though.

I assume the server starts fine however?


When reproducing a game bug in a vanilla save, make sure you are using the same mode _(singleplayer/co-op/dedicated multiplayer, survival/creative)_ as what you were using when the issue happened in the scenario.
To see a list of known game bugs or to report a new one please see: https://empyriononline.com/forums/bugs.24/

**Comment by wunz1** [comment]
Yeah server seems to start and run fine so far

**Comment by RavienGaming** [comment]
Weird. I guess it's just one of those errors that is thrown but doesn't actually matter.
